services:
  - type: web
    name: MINI JESUS-pair-site
    env: docker
    plan: free
    branch: main
    repo: https://github.com/DAWENS-BOY904/MINI-CRASH-pair
    dockerfilePath: ./Dockerfile
    autoDeploy: true
